"""
alerts/alerter.py

Sends email alerts when a malicious query is detected.
Non-blocking: alerts are sent in a background thread.
"""

import smtplib
import threading
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional, List

from config.settings import SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, ALERT_TO

# ─────────────────────────────────────────────
# Internal email sender
# ─────────────────────────────────────────────


def _send_email(subject: str, body_html: str):
    try:

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = SMTP_USER
        msg["To"] = ALERT_TO

        msg.attach(MIMEText(body_html, "html"))
        print("SMTP_HOST =", SMTP_HOST)
        print("SMTP_PORT =", SMTP_PORT)

        with smtplib.SMTP_SSL(SMTP_HOST, 465, timeout=10) as server:
          server.login(SMTP_USER, SMTP_PASSWORD)
          server.sendmail(SMTP_USER, ALERT_TO, msg.as_string())

        print(f"[Alert] Email sent to {ALERT_TO}")

    except Exception as e:
        print(f"[Alert] Failed to send email: {e}")


# ─────────────────────────────────────────────
# Public alert function
# ─────────────────────────────────────────────


def send_alert(
    user: str,
    ip: str,
    query: str,
    anomaly_score: float,
    explanation: Optional[List[str]] = None,
    timestamp: Optional[str] = None,
):
    """
    Send an async alert email — non-blocking.
    """
    ts = timestamp or datetime.utcnow().isoformat() + "Z"

    subject = f"🚨 AI-DB-IDPS ALERT [{user}@{ip}]"

    # Format explanation list
    if isinstance(explanation, list):
        reason_html = "<ul>" + "".join(f"<li>{r}</li>" for r in explanation) + "</ul>"

    elif isinstance(explanation, str):
        reason_html = f"<p>{explanation}</p>"

    else:
        reason_html = "<p>Anomalous query detected by ML model</p>"

    # HTML Email Body
    body = f"""
<html>
<body style="font-family:monospace;background:#111;color:#eee;padding:20px;">

<h2 style="color:#ff4444;">🚨 Intrusion Detected & Blocked</h2>

<table style="border-collapse:collapse;width:100%">
  <tr>
    <td style="color:#aaa;padding:6px">Timestamp</td>
    <td style="padding:6px">{ts}</td>
  </tr>
  <tr>
    <td style="color:#aaa;padding:6px">User</td>
    <td style="padding:6px"><b>{user}</b></td>
  </tr>
  <tr>
    <td style="color:#aaa;padding:6px">IP Address</td>
    <td style="padding:6px"><b>{ip}</b></td>
  </tr>
  <tr>
    <td style="color:#aaa;padding:6px">Anomaly Score</td>
    <td style="padding:6px;color:#ff9900"><b>{anomaly_score:.6f}</b></td>
  </tr>
</table>

<h3 style="color:#ff4444;">🚨 Reasons:</h3>
{reason_html}

<h3 style="color:#ff4444;">Blocked Query:</h3>
<pre style="background:#1a1a1a;padding:12px;border-left:3px solid #ff4444;
            color:#ffcc00;overflow-x:auto;">{query}</pre>

<p style="color:#666;font-size:12px;">
  Generated by AI-DB-IDPS — Investigate immediately.
</p>

</body>
</html>
"""

    # Run in background thread (non-blocking)
    thread = threading.Thread(target=_send_email, args=(subject, body), daemon=True)
    thread.start()
